### ISSUE TITLE
Rails 3 

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#58]
**dan morris** opened this issue

Any idea why i&rsquo;m getting this error?

undefined method `state_machine&rsquo; 

I&rsquo;ve installed the 0.9.2 gem in a Rails beta 3 app.

I&rsquo;ve tried a few things and got a different problem before where transitioning wouldn&rsquo;t work at all.

Many thanks!

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/48)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
I&rsquo;ve verified that state_machine works in Rails 3.0.0.beta4.  I would double-check that you&rsquo;ve defined your gems properly in your Gemfile.  For example, mine is:

 @@@ ruby
source &rsquo;http://gemcutter.org&rsquo;

gem "rails", "3.0.0.beta4"
gem &rsquo;ruby-graphviz&rsquo;, :require => &rsquo;graphviz&rsquo;
gem &rsquo;state_machine&rsquo;, &rsquo;0.9.2&rsquo;
gem "sqlite3-ruby", :require => "sqlite3"
 @@@

Beyond that, you may want to check that you don&rsquo;t have conflicting gems installed system-wide like multiple beta versions of Rails.

Hope this helps.

**Comment by obrie** [comment]
**dan morris** commented

Thanks for the reply!

My gemfile looks correct, i&rsquo;m using edge rails and 0.9.2 of state_machine.

Do you have a rails 3 beta3/4 sample app I could checkout? It might help to diagnose.

Many thanks!
Dan
