### ISSUE TITLE
Not working with ruby 2.0?

### ISSUE THREAD

**Issue by jtippett** [pluginaweek/state_machine#238]
Hi, installed ruby 2.0 to check it out, and it seems I can't init anything with a state_machine attached. Getting this error: 

Loading development environment (Rails 3.2.12)
2.0.0p0 :001 > j = Job.new
NoMethodError: undefined method `remove_attributes_protected_from_mass_assignment' for #<Job not initialized>
    from /Users/james/.rvm/gems/ruby-2.0.0-p0/gems/activemodel-3.2.12/lib/active_model/attribute_methods.rb:407:in`method_missing'
    from /Users/james/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-3.2.12/lib/active_record/attribute_methods.rb:149:in `method_missing'
    from /Users/james/.rvm/gems/ruby-2.0.0-p0/gems/default_value_for-2.0.1/lib/default_value_for.rb:133:in`initialize'
    from /Users/james/.rvm/gems/ruby-2.0.0-p0/gems/state_machine-1.1.2/lib/state_machine/integrations/active_record.rb:461:in `initialize'

Any ideas as to what might be the issue? 

Cheers! james

edit: er, it's default_value_for causing the problem. I was blind to it until I pasted that on the issue. Carry on, nothing to see here ...

**Comment by sheerun** [comment]
I get this error too. What's the solution?

**Comment by concept47** [comment]
Just upgrade your version of default_value_for. 
I was on 1.0.7, upgraded to 2.0.3 and the problems went away
